---
namespace: moc-ops
commonLabels:
  app: netbox

resources:
  - ../base

generators:
  - secret-generator.yml

patches:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: netbox-nginx
    spec:
      template:
        spec:
          initContainers:
            - name: nginx-init
              image: image-registry.openshift-image-registry.svc:5000/moc-ops/netbox-init:3
              command: ["sh"]
              args: ["-c", "tar -C /data/nginx -cf- . | tar -C /vol/copy-to -xf-"]
              volumeMounts:
                - mountPath: /vol/copy-to
                  name: netbox-nginx-config
