---
commonLabels:
  app: netbox

resources:
  - deployment-infra.yml
  - deployment-netbox.yml
  - volumes.yml
  - services.yml
  - routes.yml

configMapGenerator:
  - name: netbox-config
    envs:
      - netbox-config.env
  - name: netbox-init-scripts
    files:
      - init-netbox-data.sh
