---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-cache
---
apiVersion: v1
kind: Service
metadata:
  name: netbox
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 8001
      targetPort: netbox
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: netbox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: nginx
