apiVersion: v1
kind: Secret
metadata:
    name: netbox
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:16AfJ5BbTbk0gHOJzjR/bGxzsdhIG6D2LA==,iv:ykI2IFIVF1bDlLkZX/yJL8ueWqYv7EhiQQ6dFXDmxDY=,tag:2Q3wU2pM1Wi3P9jhxZa20w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:WrM0UvqeA0BX4b2uY8bN8mbgrNMkJzOKpvBPS0kEyrblKzEMh+oqyhHZXzsTtVr2u5k=,iv:ZiphwJbaev3qWiuuDIUTNo74Er4nY/Sev7WoCCx38Js=,tag:xqSgmEx1KUBUlEuZeTgu3g==,type:str]
    SUPERUSER_API_TOKEN: ENC[AES256_GCM,data:Bd2r3EM/GPRaSDoaGomczwmylGvI6BS/Vx7hDvviVtPJOTvbG++dn4pUmawj5BGhSzw=,iv:oNfACnkDAmUZbaJv9M03jtHxAzKJOIeEMqdlRCUijYg=,tag:vlkRffjtwcvCDrvZpiM6WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-31T04:07:11Z'
    mac: ENC[AES256_GCM,data:t5TPH0W0ppNFfiE3UCywbbCON3ebtg89mdohmBlfbVQIqFbsQqgyTlwjnT3cAJEF7nve9EAklxElgjtuIL4z/G6vhc3roH/73iKVpBk7P8bKDy6f4AO03l0yCpRglZHjt0uZn1psquTyerD51rSw+EjmNK3vbOmuA/EXHWaW+6c=,iv:1BG7tgdrjYw8L/6Yp31KhS/AJDxvQpWuDa3KaG5al/o=,tag:3V1ufGUD1YE+F8AHIsD7OQ==,type:str]
    pgp:
    -   created_at: '2020-10-31T04:07:10Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA0Jtk4Lf1qepAQgAmf8wOsPV0gIWZUmVyBoE7v24wV28hyBYeygAMzmhaill
            p2VU4TeUsNI6K+OA4RRjrqsZjIRDeCOda4xG7mArH5Hf0H1lEuPPJXM6aUehd+9O
            ttHYQVUXeKhxQSu7Kf2EjyIn5Sgi/Unx9Mc8yLEXN9nP1M87CpZy9XMxI/FWplws
            VNMIZ8/RqJbdkhKmGj8hMB2hBU6GXnYWOiMfOF8pUvjCYSuvaS1Hlb8G3NHo00k9
            Bq0829phhrEyGi37fKUE3pBLOjcvYkAOy4N1qmQdlTwbyT2vQEqU3Bw8wyScv474
            Bm11o9IHVnrjFU6wdFZLvvm7LfzG7i8FKlTkBgBNINLgAeR2Oq8SfwRuGgyNHSif
            /8Mm4TmE4A3gCeF4HOBt4l9upsbgkOW1ENCQmQVQGcCV7h4rfUcnm6fUf7eYhlVD
            nZwwIeZNhOA15IsrgQHfX5xQDzubg0Rwea3ie30kZuE/ZQA=
            =K4Ba
            -----END PGP MESSAGE-----
        fp: 3E70A502BB5255B6BB8E86BE362D63A80853D4CF
    encrypted_regex: ^(data|stringData)$
    version: 3.6.0
